//! Plain-text CLI output helpers — the non-TUI counterpart to [`crate::ui`].
//!
//! These centralize the load-bearing stdout/stderr split: the shell wrapper
//! generated by `gx setup` captures stdout to `cd` into a path, so [`nav_path`]
//! is the ONLY thing gx writes to stdout. Every diagnostic — cancellations,
//! warnings, confirmation prompts — goes to stderr.

use std::io::{self, IsTerminal};
use std::path::Path;

/// "Cancelled" to stderr — the user aborted an interactive flow.
pub fn cancelled() {
    eprintln!("Cancelled");
}

/// A `warning: <msg>` diagnostic to stderr.
pub fn warn(msg: impl std::fmt::Display) {
    eprintln!("warning: {msg}");
}

/// Build a confirmation prompt body: a header, a blank line, then `  - item`
/// bullets. Shared by the workspace remove/clean/prune confirmations.
pub fn bulleted_prompt(
    header: impl Into<String>,
    items: impl IntoIterator<Item = String>,
) -> String {
    let mut lines = vec![header.into(), String::new()];
    lines.extend(items.into_iter().map(|item| format!("  - {item}")));
    lines.join("\n")
}

/// Print the path the shell wrapper should `cd` into. This is the only thing gx
/// writes to stdout; when stdout is a TTY (so the wrapper is not capturing it),
/// a hint to stderr explains why gx could not cd for the user.
pub fn nav_path(path: &Path) {
    let path = path.canonicalize().unwrap_or_else(|_| path.to_path_buf());
    println!("{}", path.display());

    if io::stdout().is_terminal() {
        eprintln!();
        eprintln!("hint: gx printed the path but could not cd for you.");
        eprintln!(
            "      Add 'eval \"$(gx setup)\"' to your shell config (and use 'gx' from your PATH,"
        );
        eprintln!("      not './gx') to switch workspaces automatically.");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bulleted_prompt_shape() {
        let prompt = bulleted_prompt("Remove 2 workspaces?", ["a".to_string(), "b".to_string()]);
        assert_eq!(prompt, "Remove 2 workspaces?\n\n  - a\n  - b");
    }

    #[test]
    fn test_bulleted_prompt_no_items() {
        assert_eq!(bulleted_prompt("Header", std::iter::empty()), "Header\n");
    }
}
